name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: deploy
  jobs:
  - job: deploy
    displayName: Deploy containers to  dockerhub
    variables:
      - group: deployment-information
    steps:
    - task: Docker@2
      displayName: Login to dockerhub
      inputs:
        command: login
        containerRegistry: dockerhub
    - script: |
        set -xv  # Echo commands before they are run
        export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
        if [[ "$TAG" == *stable* ]]; then export BUILD_TYPE=stable; else export BUILD_TYPE=latest; fi
        export IMAGE=cccs/assemblyline-service-sigma/assemblyline-service-sigma
        docker build --build-arg version=$TAG -t $IMAGE:$TAG -t $IMAGE:$BUILD_TYPE -f ./Dockerfile .
        docker push $IMAGE
      displayName: Build and deploy containers to dockerhub
